mysql:
  build: .
  dockerfile: Dockerfile-MySQL
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: root
    MYSQL_PASSWORD: mysqlpassword
    MYSQL_DATABASE: local_db
    TZ: "Asia/Tokyo"
  container_name: local_db
  ports:
    - 3306:3306
